### ISSUE TITLE
Example code for STM32

### ISSUE THREAD

**Issue by va7wv** [Pablo-Jean/buzzer#1]
Any chance you could provide examples on how to use?

**Comment by Pablo-Jean** [comment]
Hi!
Sure, I will improve the code, and this week I will provide some example for how to implement on STM32.

**Comment by va7wv** [comment]
That is very kind of you.  If there is any way I can support you, please let me know.

**Comment by Pablo-Jean** [comment]
Hi @advlogic, I have improved the code and added the example.
This week I will try to write the README file.
